import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import WebSocket from 'ws';
const base = process.argv[2] || 'http://localhost:8787';
const socketBase = base.replace(/^http/, 'ws');
const response = await fetch(base + '/api/reader-room', { method: 'POST' });
assert.equal(response.status, 201);
const { code, readerToken } = await response.json();
assert.match(code, /^\d{6}$/);
const clients = [];
async function connect (role, token = randomUUID()) {
  const ws = new WebSocket(`${socketBase}/reader-room?${new URLSearchParams({ code, role, token })}`, { headers: { 'User-Agent': 'NSB integration check' } });
  const c = { ws, token, messages: [], state: null };
  ws.on('message', data => { const m = JSON.parse(data); c.messages.push(m); if (m.type === 'state') c.state = m; });
  clients.push(c);
  await wait(() => c.messages.length);
  return c;
}
async function wait (fn) { for (let i = 0; i < 500; i++) { if (fn()) return; await new Promise(resolve => setTimeout(resolve, 20)); } throw Error('Timed out'); }
const send = (c, type, extra = {}) => c.ws.send(JSON.stringify({ type, ...extra }));
try {
  const host = await connect('reader', readerToken);
  const a = await connect('player');
  const b = await connect('player');
  const c = await connect('player');
  await wait(() => Object.keys(host.state.players).length === 3);
  assert.deepEqual(host.state.teams.map(t => t.length), [2, 1]);
  const ids = Object.keys(host.state.players);
  const aid = ids.find(id => host.state.players[id].username === a.state.username);
  const cid = ids.find(id => host.state.players[id].username === c.state.username);
  send(host, 'move-player', { id: cid, team: 1, index: 0 });
  await wait(() => c.state.title === 'B Captain');
  send(host, 'next', { setName: '2009 NSB Sample Set 1', packetNumber: 3, category: 'Math' });
  await wait(() => host.state.pair && a.state.canBuzz);
  const questionId = host.state.pair.tossup._id;
  send(a, 'judge', { correct: true });
  send(a, 'next');
  send(a, 'kick', { id: cid });
  send(a, 'buzz');
  await wait(() => host.state.pending);
  send(b, 'buzz');
  assert.equal(host.state.pending.id, aid);
  assert.equal(host.state.pending.interrupt, true);
  assert.equal(host.state.pair.tossup._id, questionId);
  assert.deepEqual(host.state.scores, [0, 0]);
  assert.equal(host.state.players[cid].kicked, undefined);
  for (const m of a.messages.filter(m => m.type === 'state')) {
    assert.deepEqual(Object.keys(m).sort(), ['type', 'role', 'username', 'team', 'title', 'canBuzz', 'buzzed', 'readerOnline'].sort());
  }
  send(host, 'judge', { correct: false, interrupt: true });
  await wait(() => host.state.result === false);
  assert.deepEqual(host.state.scores, [0, 4]);
  send(host, 'judge', { correct: true, interrupt: false });
  await wait(() => host.state.result === true);
  assert.deepEqual(host.state.scores, [4, 0]);
  send(host, 'next');
  await wait(() => host.state.kind === 'bonus');
  assert.equal(host.state.pair.bonus.number, host.state.pair.tossup.number);
  assert.equal(a.state.canBuzz, false);
  send(host, 'judge', { correct: true });
  await wait(() => host.state.scores[0] === 14);
  send(host, 'next', { setName: '2009 NSB Sample Set 1', packetNumber: 3, category: 'Math' });
  await wait(() => host.state.kind === 'tossup' && host.state.pair.tossup._id !== questionId);
  send(host, 'start-timer');
  await wait(() => host.state.timer.started);
  send(a, 'buzz');
  await wait(() => host.state.pending);
  assert.equal(host.state.pending.interrupt, false);
  send(host, 'judge', { correct: false, interrupt: false });
  await wait(() => host.state.result === false);
  send(host, 'kick', { id: cid });
  await wait(() => c.messages.some(m => m.fatal));
  const kicked = await connect('player', c.token);
  assert.match(kicked.messages[0].message, /removed/);
  assert.equal(host.state.players[cid].kicked, true);
  const bad = await connect('reader');
  assert.match(bad.messages[0].message, /denied/);
  send(host, 'lock', { locked: true });
  await wait(() => host.state.locked);
  const blocked = await connect('player');
  assert.match(blocked.messages[0].message, /locked/);
  a.ws.close();
  await wait(() => host.state.players[aid].online === false);
  const reconnect = await connect('player', a.token);
  assert.equal(reconnect.state.username, a.state.username);
  assert.equal(host.state.players[aid].correct, 1);
  send(reconnect, 'set-username', { username: 'Mobile Player' });
  await wait(() => reconnect.state.username === 'Mobile Player');
  assert.equal(host.state.players[aid].username, 'Mobile Player');
  send(reconnect, 'end-room');
  send(reconnect, 'set-username', { username: 'Still Here' });
  await wait(() => reconnect.state.username === 'Still Here');
  send(host, 'end-room');
  await wait(() => reconnect.messages.some(m => m.type === 'room-ended') && host.messages.some(m => m.type === 'room-ended'));
  const ended = await connect('player');
  assert.match(ended.messages[0].message, /not found/);
  console.log('Live room checks passed, including player username updates, reader-only End, disconnecting everyone, and invalidating the code.');
} finally { for (const c of clients) c.ws.close(); }
